In [ ]:
a=[10,20,30,40]
type(a)

list

In [ ]:
a=[10,20,30,40]
type(a)
import numpy as np
x = np.array(a)
print(x)

[10 20 30 40]


In [ ]:
a=[10,20,30,40]
type(a)
import numpy as np
x = np.array(a)
type(x)

numpy.ndarray

In [ ]:
a=[1,2,3,4]
b=[2,4,6,8]
import numpy as np
x = np.array([a,b])
print(x)

[[1 2 3 4]
 [2 4 6 8]]


In [ ]:
a=[1,2,3]
b=[10,20,30]
import numpy as np
x = np.array([a,b])
print(x)

[[ 1  2  3]
 [10 20 30]]


In [ ]:
import numpy as np
x= np.array([2,4,6,8], dtype = np.float32)
print(x)

[2. 4. 6. 8.]


In [ ]:
import numpy as np
x= np.zeros((3,2))
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
x= np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
import numpy as np
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
import numpy as np
x= np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
x= np.ones(5, dtype = np.int32)
print(x)

[1 1 1 1 1]


In [ ]:
import numpy as np
x= np.random.rand(2,3)
print(x)

[[0.5532975  0.28773082 0.62668513]
 [0.72616958 0.74390829 0.91711267]]


In [ ]:
import numpy as np
np.random.randint(1,20, size = (3,3))

array([[11, 12, 11],
       [19,  7,  8],
       [16,  2,  3]])

In [ ]:
import numpy as np
np.random.randn(2,4)

array([[ 0.64288428, -0.63154114,  0.67394284,  1.22007177],
       [ 1.61283682,  0.33695516, -1.00797057, -0.67423099]])

In [ ]:
import numpy as np
x= np.random.choice([10,2,4,6,8,10,12])
print(x)

10


In [ ]:
import numpy as np
np.full((3,4),20)

array([[20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20]])

In [ ]:
import numpy as np
np.ones((2,2))*10

array([[10., 10.],
       [10., 10.]])

In [ ]:
import numpy as np
x = np.eye(3, k = 0)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
import numpy as np
np.arange(1,9,2)

array([1, 3, 5, 7])

In [ ]:
import numpy as np
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
a = [10,20,30,40,50]
x= np.array(a)
print(x)

[10 20 30 40 50]


In [ ]:
x.ndim

1

In [ ]:
b = [5,10,15,20,25]
y = np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 5 10 15 20 25]]


In [ ]:
y.ndim

2

In [ ]:
y.shape

(2, 5)

In [ ]:
y.size

10

In [ ]:
a = np.array([3,6,9,12])
print(a)

[ 3  6  9 12]


In [ ]:
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
a.reshape(2,2)

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.size

9

In [ ]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x = np.arange(1,17)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
y = x.reshape(4,4)
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
z = np.transpose(y)
print(z)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [ ]:
y.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [ ]:
a = np.arange(1,13)
print(a)
a[4:9]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([5, 6, 7, 8, 9])

In [ ]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x[1,2]

np.int64(6)

In [ ]:
x[1][2]

np.int64(6)

In [ ]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [ ]:
x = np.vstack((a,b))
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
x = np.hstack((a,b))
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [ ]:
a = np.arange(10,21,2)
b = np.array([[2],[2]])
print(a)
print(b)

[10 12 14 16 18 20]
[[2]
 [2]]


In [ ]:
z=(a+b)
print(z)

[[12 14 16 18 20 22]
 [12 14 16 18 20 22]]


In [ ]:
a = np.arange(10,21,2)
a+2

array([12, 14, 16, 18, 20, 22])

In [ ]:
a-b

array([[ 8, 10, 12, 14, 16, 18],
       [ 8, 10, 12, 14, 16, 18]])

In [ ]:
a*b

array([[20, 24, 28, 32, 36, 40],
       [20, 24, 28, 32, 36, 40]])

In [ ]:
import numpy as np
a = np.ones((3,3))
b = np.array([2])
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[2]


In [ ]:
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [ ]:
a-b

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [ ]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(a+5)

[[6. 5. 5. 5.]
 [5. 6. 5. 5.]
 [5. 5. 6. 5.]
 [5. 5. 5. 6.]]


In [ ]:
a-1

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [ ]:
a*2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [ ]:
print(a/0.5)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


In [ ]:
np.sin(a)

array([[0.84147098, 0.        , 0.        , 0.        ],
       [0.        , 0.84147098, 0.        , 0.        ],
       [0.        , 0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.        , 0.84147098]])

In [ ]:
np.cos(a)

array([[0.54030231, 1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 0.54030231]])

In [ ]:
np.sqrt(a)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
a = np.arange(5,15,2)
print(a)
x = np.log(a)
print(x)

[ 5  7  9 11 13]
[1.60943791 1.94591015 2.19722458 2.39789527 2.56494936]


In [7]:
a = np.arange(5,15,2)
print(a)
x = np.exp(a)
print(x)

[ 5  7  9 11 13]
[1.48413159e+02 1.09663316e+03 8.10308393e+03 5.98741417e+04
 4.42413392e+05]


In [ ]:
a = np.arange(5,15,2)
print(a)

[ 5  7  9 11 13]


In [ ]:
x = np.mean(a)
print(x)

9.0


In [ ]:
x = np.median(a)
print(x)

9.0


In [ ]:
x = np.std(a)
print(x)

2.8284271247461903


In [4]:
import numpy as np
a = np.arange(5,15,2)
x=np.var(a)
print(x)

8.0


In [ ]:
a = np.array([[1,6],[4,3]])
print(a)

[[1 6]
 [4 3]]


In [ ]:
print(np.min(a, axis=0))

[1 3]


In [ ]:
print(np.min(a, axis=1))

[1 3]


In [ ]:
print(np.max(a, axis=0))

[4 6]


In [ ]:
print(np.max(a, axis=1))

[6 4]


In [ ]:
a = np.array([1,4,9,16,25])
print(a)

[ 1  4  9 16 25]


In [ ]:
x = np.sort(a, kind ='mergesort')
print(x)

[ 1  4  9 16 25]


In [17]:
a = np.array([2,3,7,15,25])
x = np.unique(a)
print(x)

[ 2  3  7 15 25]


In [14]:
a = np.array([1,4,9,16,25])
x = np.argsort(a)
print(x)

[0 1 2 3 4]


In [15]:
a = np.array([1,4,9,16,25])
x = np.nonzero(a)
print(x)

(array([0, 1, 2, 3, 4]),)


In [ ]:
A= np.arange(0,9).reshape(3,3)
B= np.ones((3,3))
print(A)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [ ]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [22]:
import numpy as np
a= np.array([3.2,0.25,5.7,1.5,3.1457])
x = np.round(a)
print(np.round(a, decimals=2))

[3.2  0.25 5.7  1.5  3.15]


In [24]:
import numpy as np
a= np.array([3.7,0.75,-2.6,-1.5])
x = np.ceil(a)
print(f"Original: {a}")
print(f"Ceiling:  {x}")

Original: [ 3.7   0.75 -2.6  -1.5 ]
Ceiling:  [ 4.  1. -2. -1.]


In [25]:
import numpy as np
a= np.array([3.7,0.75,-2.6,-1.5])
x = np.floor(a)
print(f"Original: {a}")
print(f"Floor:  {x}")

Original: [ 3.7   0.75 -2.6  -1.5 ]
Floor:  [ 3.  0. -3. -2.]


In [35]:
import numpy as np
matrix = np.array([[1, 2, 4],
                   [3, 7 ,9 ]])
x = np.ravel(matrix)

print(f"Original:{matrix}")
print(f"Raveled: {x}")

Original:[[1 2 4]
 [3 7 9]]
Raveled: [1 2 4 3 7 9]


In [34]:
import numpy as np
matrix = np.array([[10, 30,],
                    [20, 50,]])
x = matrix.flatten()
print(f"Original:{matrix}")
print(f"Flattened: {x}")

Original:[[10 30]
 [20 50]]
Flattened: [10 30 20 50]
